channels:
  - r
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
- r-ggrepel=0.8.2
- r-ggthemes=4.2.0
- r-askpass=1
- r-assertthat=0.2.1
- r-backports=1.1.4
- r-base=3.6.1
- r-base64enc=0.1_3
- r-bh=1.69.0_1
- r-bit=1.1_14
- r-bit64=0.9_7
- r-bitops=1.0_6
- r-blob=1.1.1
- r-boot=1.3_20
- r-broom=0.5.2
- r-callr=3.2.0
- r-caret=6.0_83
- r-catools=1.17.1.2
- r-cellranger=1.1.0
- r-class=7.3_15
- r-cli=1.1.0
- r-clipr=0.6.0
- r-clisymbols=1.2.0
- r-cluster=2.0.8
- r-codetools=0.2_16
- r-colorspace=1.4_1
- r-config=0.3
- r-crayon=1.3.4
- r-curl=3.3
- r-data.table=1.12.2
- r-dbi=1.0.0
- r-dbplyr=1.4.0
- r-desc=1.2.0
- r-devtools=2.0.2
- r-dichromat=2.0_0
- r-digest=0.6.18
- r-dplyr=0.8.0.1
- r-ellipsis=0.1.0
- r-essentials=3.6.0
- r-evaluate=0.13
- r-fansi=0.4.0
- r-forcats=0.4.0
- r-foreach=1.4.4
- r-foreign=0.8_71
- r-forge=0.2.0
- r-formatr=1.6
- r-fs=1.2.7
- r-generics=0.0.2
- r-ggplot2=3.1.1
- r-gh=1.0.1
- r-git2r=0.25.2
- r-glmnet=2.0_16
- r-glue=1.3.1
- r-gower=0.2.0
- r-gtable=0.3.0
- r-haven=2.1.0
- r-hexbin=1.27.2
- r-highr=0.8
- r-hms=0.4.2
- r-htmltools=0.3.6
- r-htmlwidgets=1.3
- r-httpuv=1.5.1
- r-httr=1.4.0
- r-ini=0.3.1
- r-ipred=0.9_8
- r-irdisplay=0.7.0
- r-irkernel=0.8.15
- r-iterators=1.0.10
- r-jsonlite=1.6
- r-kernsmooth=2.23_15
- r-knitr=1.22
- r-labeling=0.3
- r-later=0.8.0
- r-lattice=0.20_38
- r-lava=1.6.5
- r-lazyeval=0.2.2
- r-lubridate=1.7.4
- r-magrittr=1.5
- r-maps=3.3.0
- r-markdown=0.9
- r-mass=7.3_51.3
- r-matrix=1.2_17
- r-memoise=1.1.0
- r-mgcv=1.8_28
- r-mime=0.6
- r-miniui=0.1.1.1
- r-modelmetrics=1.2.2
- r-modelr=0.1.4
- r-mongolite=2.0.1
- r-munsell=0.5.0
- r-nlme=3.1_139
- r-nnet=7.3_12
- r-numderiv=2016.8_1
- r-odbc=1.1.5
- r-openssl=1.3
- r-packrat=0.5.0
- r-pbdzmq=0.3_3
- r-pillar=1.3.1
- r-pkgbuild=1.0.3
- r-pkgconfig=2.0.2
- r-pkgload=1.0.2
- r-pki=0.1_5.1
- r-plogr=0.2.0
- r-plyr=1.8.4
- r-prettyunits=1.0.2
- r-processx=3.3.0
- r-prodlim=2018.04.18
- r-profvis=0.3.5
- r-progress=1.2.0
- r-promises=1.0.1
- r-ps=1.3.0
- r-purrr=0.3.2
- r-quantmod=0.4_14
- r-r2d3=0.2.3
- r-r6=2.4.0
- r-randomforest=4.6_14
- r-rappdirs=0.3.1
- r-rbokeh=0.6.3
- r-rcmdcheck=1.3.2
- r-rcolorbrewer=1.1_2
- r-rcpp=1.0.1
- r-rcpproll=0.3.0
- r-rcurl=1.95_4.12
- r-readr=1.3.1
- r-readxl=1.3.1
- r-recipes=0.1.5
- r-recommended=3.6.0
- r-rematch=1.0.1
- r-remotes=2.0.4
- r-repr=0.19.2
- r-reprex=0.2.1
- r-reshape2=1.4.3
- r-rjava=0.9_11
- r-rjdbc=0.2_7.1
- r-rjsonio=1.3_1.1
- r-rlang=0.3.4
- r-rmarkdown=1.12
- r-rpart=4.1_15
- r-rprojroot=1.3_2
- r-rsconnect=0.8.13
- r-rsqlite=2.1.1
- r-rvest=0.3.3
- r-scales=1.0.0
- r-selectr=0.4_1
- r-sessioninfo=1.1.1
- r-shiny=1.3.2
- r-sourcetools=0.1.7
- r-sparklyr=1.0.0
- r-spatial=7.3_11
- r-squarem=2017.10_1
- r-stringi=1.4.3
- r-stringr=1.4.0
- r-survival=2.44_1.1
- r-sys=3.2
- r-tibble=2.1.1
- r-tidyr=0.8.3
- r-tidyselect=0.2.5
- r-tidyverse=1.2.1
- r-timedate=3043.102
- r-tinytex=0.12
- r-ttr=0.23_4
- r-usethis=1.5.0
- r-utf8=1.1.4
- r-uuid=0.1_2
- r-viridislite=0.3.0
- r-whisker=0.3_2
- r-withr=2.1.2
- r-xfun=0.6
- r-xml2=1.2.0
- r-xopen=1.0.0
- r-xtable=1.8_4
- r-xts=0.11_2
- r-yaml=2.2.0
- r-zoo=1.8_6
- rpy2=3.3.2
- pandas=1.0.5
- cufflinks-py=0.17.3
- bioconductor-biobase=2.46.0=r36h516909a_0
- bioconductor-biocgenerics=0.32.0=r36_0
- bioconductor-biomformat=1.14.0=r36_0
- bioconductor-biostrings=2.54.0=r36h516909a_0
- bioconductor-ihw=1.14.0=r36_0
- bioconductor-iranges=2.20.0=r36h516909a_0
- bioconductor-limma=3.42.0=r36h516909a_0
- bioconductor-lpsymphony=1.14.0=r36he1b5a44_0
- bioconductor-metagenomeseq=1.28.0=r36_0
- bioconductor-multtest=2.42.0=r36h516909a_0
- bioconductor-phyloseq=1.30.0=r36_0
- bioconductor-rhdf5=2.30.0=r36he1b5a44_0
- bioconductor-rhdf5lib=1.8.0=r36h516909a_0
- bioconductor-s4vectors=0.24.0=r36h516909a_0
- bioconductor-wrench=1.4.0=r36_0
- bioconductor-xvector=0.26.0=r36h516909a_0
- bioconductor-zlibbioc=1.32.0=r36h516909a_0
- ipywidgets=7.5.1
- numpy=1.18.1
- numpy-base=1.18.1
- pip=20.0.2
- pip:
  - ipython-sql==0.3.9
